chore: auto-format shell
Make `tox` -e do_format` and `tox -e check_format` enforce
formatting of json and shell scripts.

Remove unmaintained shell scripts.

Update GH Actions.

```
shfmt --list --case-indent --indent=4 --space-redirects -w
```

Using v3.12.0

diff --git a/tools/build-on-freebsd b/tools/build-on-freebsd
--- a/tools/build-on-freebsd
+++ b/tools/build-on-freebsd
@@ -8,7 +8,10 @@
 
 set -eux
 
-fail() { echo "FAILED:" "$@" 1>&2; exit 1; }
+fail() {
+    echo "FAILED:" "$@" 1>&2
+    exit 1
+}
 
 PYTHON="${PYTHON:-python3}"
 if [ ! $(which ${PYTHON}) ]; then
