chore: format shell scripts
Also add a tox command to run this.

```
shfmt --list --case-indent --indent=4 --space-redirects -w
```

Using v3.12.0

diff --git a/tools/cloud-init-per b/tools/cloud-init-per
--- a/tools/cloud-init-per
+++ b/tools/cloud-init-per
@@ -5,7 +5,7 @@ DATA_PRE="/var/lib/cloud/sem/bootper"
 INST_PRE="/var/lib/cloud/instance/sem/bootper"
 
 Usage() {
-   cat <<EOF
+    cat << EOF
 Usage: ${0##*/} frequency name cmd [ arg1 [ arg2 [ ... ] ]
    run cmd with arguments provided.
 
@@ -20,38 +20,51 @@ Usage: ${0##*/} frequency name cmd [ arg1 [ arg2 [ ... ] ]
 EOF
 }
 error() { echo "$@" 1>&2; }
-fail() { [ $# -eq 0 ] || error "$@"; exit 1; }
+fail() {
+    [ $# -eq 0 ] || error "$@"
+    exit 1
+}
 
 # support the old 'cloud-init-run-module freq name "execute" cmd arg1'
 # if < 3 arguments, it will fail below on usage.
 if [ "${0##*/}" = "cloud-init-run-module" ]; then
-   if [ $# -le 2 -o "$3" = "execute" ]; then
-      error "Warning: ${0##*/} is deprecated. Please use cloud-init-per."
-      freq=$1; name=$2; 
-      [ $# -le 2 ] || shift 3;
-      set -- "$freq" "$name" "$@"
-   else
-      fail "legacy cloud-init-run-module only supported with module 'execute'"
-   fi
+    if [ $# -le 2 -o "$3" = "execute" ]; then
+        error "Warning: ${0##*/} is deprecated. Please use cloud-init-per."
+        freq=$1
+        name=$2
+        [ $# -le 2 ] || shift 3
+        set -- "$freq" "$name" "$@"
+    else
+        fail "legacy cloud-init-run-module only supported with module 'execute'"
+    fi
 fi
 
-[ "$1" = "-h" -o "$1" = "--help" ] && { Usage ; exit 0; }
-[ $# -ge 3 ] || { Usage 1>&2; exit 1; }
+[ "$1" = "-h" -o "$1" = "--help" ] && {
+    Usage
+    exit 0
+}
+[ $# -ge 3 ] || {
+    Usage 1>&2
+    exit 1
+}
 freq=$1
 name=$(echo $2 | sed 's/-/_/g')
-shift 2;
+shift 2
 
 [ "${name#*/}" = "${name}" ] || fail "name cannot contain a /"
 [ "$(id -u)" = "0" ] || fail "must be root"
 
 case "$freq" in
-   once|always) sem="${DATA_PRE}.$name.$freq";;
-   instance) sem="${INST_PRE}.$name.$freq";;
-   *) Usage 1>&2; fail "invalid frequency: $freq";;
+    once | always) sem="${DATA_PRE}.$name.$freq" ;;
+    instance) sem="${INST_PRE}.$name.$freq" ;;
+    *)
+        Usage 1>&2
+        fail "invalid frequency: $freq"
+        ;;
 esac
 
 [ -d "${sem%/*}" ] || mkdir -p "${sem%/*}" ||
-   fail "failed to make directory for ${sem}"
+    fail "failed to make directory for ${sem}"
 
 # Rename legacy sem files with dashes in their names. Do not overwrite existing
 # sem files to prevent clobbering those which may have been created from calls
@@ -63,5 +76,5 @@ sem_legacy=$(echo $sem | sed 's/_/-/g')
 "$@"
 ret=$?
 printf "%s\t%s\n" "$ret" "$(date +%s)" > "$sem" ||
-   fail "failed to write to $sem"
+    fail "failed to write to $sem"
 exit $ret
