ds-identify: Call blkid with a list of devices.
On a system with many block devices (or "virtual" block devices such as
lvm/device-mapper ... ), running blkid can be very slow.  ds-identify is
using it to identify filesystems that may have a config disk of different
types.

If we accept limiting the search to "real" block devices based on name,
then we dramatically reduce ds-identify's load in early boot when lvm and
other devices are coming up.

This limits the search by name to those devices that do not match:

    dm-* md*

For reference, running blkid on non-existant block device still
exits success if it found any devices.
This will fail:

  $ blkid -c /dev/null -o export /dev/does-not-exist ; echo $?
  2

But this will succeed as long as any device in the list existed:

  $ blkid -c /dev/null -o export /dev/sd* /dev/does-not-exist ; echo $?
  0

diff --git a/tools/ds-identify b/tools/ds-identify
--- a/tools/ds-identify
+++ b/tools/ds-identify
@@ -271,10 +271,21 @@ ensure_sane_path() {
 blkid_export() {
     # call 'blkid -c /dev/null export', set DI_BLKID_EXPORT_OUT
     cached "$DI_BLKID_EXPORT_OUT" && return 0
-    local out="" ret=0
-    out=$(blkid -c /dev/null -o export) && DI_BLKID_EXPORT_OUT="$out" || {
+    local out="" ret=0 devs="" dev="" bn=""
+    for dev in /sys/class/block/*; do
+        bn=${dev##*/}
+        case "$bn" in
+            dm-[0-9]*|md[0-9]*) continue;;
+        esac
+        devs="${devs} /dev/$bn"
+    done
+    devs=${devs# }
+    [ -n "$devs" ] || warn "All devs in /sys/class/block/* were skipped."
+
+    out=$(blkid -c /dev/null -o export $devs) &&
+        DI_BLKID_EXPORT_OUT="$out" || {
         ret=$?
-        error "failed running [$ret]: blkid -c /dev/null -o export"
+        error "failed running [$ret]: blkid -c /dev/null -o export $devs"
         DI_BLKID_EXPORT_OUT="$UNAVAILABLE"
     }
     return $ret
