ds-identify: add OpenBSD support in uname (#4654)
by removing all the code we don't actually use

Further, we extend FreeBSD support to cover Dragonfly as well.

Sponsored by: The FreeBSD Foundation

diff --git a/tools/ds-identify b/tools/ds-identify
--- a/tools/ds-identify
+++ b/tools/ds-identify
@@ -110,11 +110,8 @@ DI_VIRT=""
 DI_PID_1_PRODUCT_NAME=""
 
 DI_UNAME_KERNEL_NAME=""
-DI_UNAME_KERNEL_RELEASE=""
 DI_UNAME_KERNEL_VERSION=""
 DI_UNAME_MACHINE=""
-DI_UNAME_NODENAME=""
-DI_UNAME_OPERATING_SYSTEM=""
 DI_UNAME_CMD_OUT=""
 
 DS_FOUND=0
@@ -235,7 +232,7 @@ dmi_decode() {
 get_dmi_field() {
     _RET="$UNAVAILABLE"
 
-    if [ "$DI_UNAME_KERNEL_NAME" = "FreeBSD" ]; then
+    if [ "$DI_UNAME_KERNEL_NAME" = "FreeBSD" -o "$DI_UNAME_KERNEL_NAME" = "Dragonfly" ]; then
         get_kenv_field "$1" || _RET="$ERROR"
         return $?
     fi
@@ -393,7 +390,7 @@ read_fs_info() {
     # - DI_ISO9660_DEVS
     # - DI_FS_UUIDS
 
-    if [ "$DI_UNAME_KERNEL_NAME" = "FreeBSD" ]; then
+    if [ "$DI_UNAME_KERNEL_NAME" = "FreeBSD" -o "$DI_UNAME_KERNEL_NAME" = "Dragonfly" ]; then
         read_fs_info_freebsd
         return $?
     else
@@ -414,7 +411,7 @@ detect_virt() {
         if [ $r -eq 0 ] || { [ $r -ne 0 ] && [ "$out" = "none" ]; }; then
             virt="$out"
         fi
-    elif [ "$DI_UNAME_KERNEL_NAME" = "FreeBSD" ]; then
+    elif [ "$DI_UNAME_KERNEL_NAME" = "FreeBSD" -o "$DI_UNAME_KERNEL_NAME" = "Dragonfly" ]; then
         # Map FreeBSD's vm_guest names to those systemd-detect-virt that
         # don't match up. See
         # https://github.com/freebsd/freebsd/blob/master/sys/kern/subr_param.c#L144-L160
@@ -532,25 +529,22 @@ read_uname_info() {
     cached "${DI_UNAME_CMD_OUT}" && return
     local out="${1:-}" ret=0 buf=""
     if [ -z "$out" ]; then
-        out=$(uname -snrvmo) || {
+        out=$(uname -svm) || {
             ret=$?
-            error "failed reading uname with 'uname -snrvmo'"
+            error "failed reading uname with 'uname -svm'"
             return $ret
         }
     fi
     # shellcheck disable=2086
     set -- $out
     DI_UNAME_KERNEL_NAME="$1"
-    DI_UNAME_NODENAME="$2"
-    DI_UNAME_KERNEL_RELEASE="$3"
-    shift 3
-    while [ $# -gt 2 ]; do
+    shift
+    while [ $# -gt 1 ]; do
         buf="$buf $1"
         shift
     done
     DI_UNAME_KERNEL_VERSION="${buf# }"
     DI_UNAME_MACHINE="$1"
-    DI_UNAME_OPERATING_SYSTEM="$2"
     DI_UNAME_CMD_OUT="$out"
     return 0
 }
@@ -1573,8 +1567,7 @@ _print_info() {
     vars="DMI_PRODUCT_NAME DMI_SYS_VENDOR DMI_PRODUCT_SERIAL"
     vars="$vars DMI_PRODUCT_UUID PID_1_PRODUCT_NAME DMI_CHASSIS_ASSET_TAG"
     vars="$vars DMI_BOARD_NAME FS_LABELS ISO9660_DEVS KERNEL_CMDLINE VIRT"
-    vars="$vars UNAME_KERNEL_NAME UNAME_KERNEL_RELEASE UNAME_KERNEL_VERSION"
-    vars="$vars UNAME_MACHINE UNAME_NODENAME UNAME_OPERATING_SYSTEM"
+    vars="$vars UNAME_KERNEL_NAME UNAME_KERNEL_VERSION UNAME_MACHINE"
     vars="$vars DSNAME DSLIST"
     vars="$vars MODE ON_FOUND ON_MAYBE ON_NOTFOUND"
     for v in ${vars}; do
