combine map_sysfs_to_dmi and the actual dmidecode call to simplify code-flow
thanks to @smoser for the review and hints

diff --git a/tools/ds-identify b/tools/ds-identify
--- a/tools/ds-identify
+++ b/tools/ds-identify
@@ -179,33 +179,34 @@ debug() {
     echo "$@" 1>&3
 }
 
-map_sysfs_to_dmi() {
-    case "$@" in
+dmi_decode() {
+    local sys_field="$1" dmi_field="" val=""
+    command -v dmidecode >/dev/null 2>&1 || {
+        warn "No dmidecode program. Cannot read $sys_field."
+        return 1
+    }
+    case "$1" in
         sys_vendor) _RET="system-manufacturer";;
         product_name) _RET="system-product-name";;
         product_uuid) _RET="system-uuid";;
         product_serial) _RET="system-serial-number";;
-        chassis-asset-tag) _RET="chassis_asset_tag";;
-        *) return 1;;
+        chassis_asset_tag) _RET="chassis-asset-tag";;
+        *) error "Unknown field $sys_field. Cannot call dmidecode."
+           return 1;;
     esac
+    val=$(dmidecode --quiet "--string=$dmi_field" 2>/dev/null) || return 1
+    _RET="$val"
 }
 
 get_dmi_field() {
     local path="${PATH_SYS_CLASS_DMI_ID}/$1"
-    if [ ! -f "$path" ] || [ ! -r "$path" ]; then
-        map_sysfs_to_dmi "$1" || {
-            _RET="$ERROR: unknown field $1"
-            return
-        }
-        local dmi_field="$_RET" dmi_value=""
-        dmi_value=$(dmidecode --quiet --string "$dmi_field") || {
-            _RET="$UNAVAILABLE"
-            return
-        }
-        _RET="$dmi_value"
+    _RET="$UNAVAILABLE"
+    if [ -f "$path" ] && [ -r "$path" ]; then
+        read _RET < "${path}" || _RET="$ERROR"
         return
     fi
-    read _RET < "${path}" || _RET="$ERROR"
+    dmi_decode "$1" || _RET="$ERROR"
+    return
 }
 
 block_dev_with_label() {
