0.7.3~bzr869-0ubuntu1 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/tools/read-dependencies b/tools/read-dependencies
--- a/tools/read-dependencies
+++ b/tools/read-dependencies
@@ -12,20 +12,21 @@ find_root() {
    [ $? -eq 0 -a -f "${topd}/setup.py" ] || return
    ROOT_DIR="$topd"
 }
+fail() { echo "$0:" "$@" 1>&2; exit 1; }
 
 if ! find_root; then
-    echo "Unable to locate 'setup.py' file that should" \
-          "exist in the cloud-init root directory." 1>&2
-    exit 1;
+    fail "Unable to locate 'setup.py' file that should " \
+         "exist in the cloud-init root directory."
 fi
 
 REQUIRES="$ROOT_DIR/Requires"
 
 if [ ! -e "$REQUIRES" ]; then
-    echo "Unable to find 'Requires' file located at $REQUIRES"
-    exit 1
+    fail "Unable to find 'Requires' file located at '$REQUIRES'"
 fi
 
-# Filter out comments and empty liens
-DEPS=$(grep -Pv "^\s*#" "$REQUIRES" | grep -Pv '^\s*$')
+# Filter out comments and empty lines
+DEPS=$(sed -n -e 's,#.*,,' -e '/./p' "$REQUIRES") &&
+   [ -n "$DEPS" ] ||
+   fail "failed to read deps from '${REQUIRES}'"
 echo "$DEPS" | sort -d -f
diff --git a/tools/read-version b/tools/read-version
--- a/tools/read-version
+++ b/tools/read-version
@@ -12,20 +12,21 @@ find_root() {
    [ $? -eq 0 -a -f "${topd}/setup.py" ] || return
    ROOT_DIR="$topd"
 }
+fail() { echo "$0:" "$@" 1>&2; exit 1; }
 
 if ! find_root; then
-    echo "Unable to locate 'setup.py' file that should" \
-          "exist in the cloud-init root directory." 1>&2
-    exit 1;
+    fail "Unable to locate 'setup.py' file that should " \
+         "exist in the cloud-init root directory."
 fi
 
 CHNG_LOG="$ROOT_DIR/ChangeLog"
 
-if [ ! -e "$CHNG_LOG" ]
-then
-    echo "Unable to find 'ChangeLog' file located at $CHNG_LOG"
-    exit 1
+if [ ! -e "$CHNG_LOG" ]; then
+    fail "Unable to find 'ChangeLog' file located at '$CHNG_LOG'"
 fi
 
-VERSION=$(grep -P "\d+.\d+.\d+:" "$CHNG_LOG"  | cut -f1 -d ":" | head -n 1)
+VERSION=$(sed -n '/^[0-9]\+[.][0-9]\+[.][0-9]\+:/ {s/://; p; :a;n; ba; }' \
+          "$CHNG_LOG") &&
+   [ -n "$VERSION" ] ||
+   fail "failed to get version from '$CHNG_LOG'"
 echo "$VERSION"
